---
kind: pipeline
type: docker
name: default

steps:
- name: compile
  image: docker.io/procsiab/texlive-it:1.2-amd64
  commands:
  - make all

- name: deploy
  image: appleboy/drone-scp:linux-amd64
  failure: ignore
  settings:
    host: sirius.node.consul
    username: publisher
    key:
      from_secret: publisher-drone-key
    port: 22
    target: /srv/book/
    source: pdf/lorenzo_prosseda.pdf
    strip_components: 1
  when:
    branch:
    - master
    status:
    - success

- name: debug
  image: docker.io/busybox:latest
  failure: ignore
  commands:
  - cat pdf/main.log
  when:
    branch:
    - master
    status:
    - failure

---
kind: signature
hmac: 54c73739398eb7f454c196f4962248b1a7bce2d7feb6e3be0bf698fe2cc5ec7b

...
