---
kind: pipeline
type: docker
name: default

steps:
- name: compile
  image: docker.io/procsiab/texlive-it:latest-amd64
  commands:
  - make all

- name: deploy
  image: appleboy/drone-scp
  failure: ignore
  settings:
    host: 192.168.1.100
    username: astro
    key:
      from_secret: astro-drone-key
    port: 22
    target: /srv/book/
    source: pdf/lorenzo_prosseda.pdf
    strip_components: 1
  when:
    branch:
    - master
    status:
    - success

- name: debug
  image: docker.io/busybox:latest
  failure: ignore
  commands:
  - cat pdf/main.log
  when:
    branch:
    - master
    status:
    - failure

---
kind: signature
hmac: d8cff27242b496c6b23407ab714a0484edcb90804b91061540b65d024c713f8d

...
